    @startuml
    title Quên mật khẩu (có lifeline đầy đủ)

    actor Actor
    boundary LoginPage
    control AuthenticationController
    entity AuthenticationService
    entity UserService
    entity passwordEncoder
    entity User
    database DB
    activate LoginPage
    Actor -> LoginPage : Click "Quên mật khẩu"
    LoginPage -> AuthenticationController : POST /forgot-password\n{email, otp, password, confirmPassword}
    activate AuthenticationController

    AuthenticationController -> AuthenticationService : forgotPassword(request)
    activate AuthenticationService

    AuthenticationService -> UserService : findByEmail(request.getEmail())
    activate UserService
    activate DB
    UserService --> DB : SELECT * FROM users WHERE email = ?

    DB --> UserService : return User
    deactivate DB

    UserService --> AuthenticationService : return User
    deactivate UserService

    alt Passwords do not match

        AuthenticationService --> AuthenticationController : throw AppException(PASSWORD_NOT_MATCHED)
        deactivate AuthenticationService
        AuthenticationController --> LoginPage : show error
        deactivate AuthenticationController
    else Passwords match
        activate AuthenticationService
        activate passwordEncoder

        AuthenticationService -> passwordEncoder : encode(password)

        passwordEncoder --> AuthenticationService : encryptedPassword
        deactivate passwordEncoder

        AuthenticationService -> User : setPassword(encryptedPassword)
        activate User
        deactivate User

        AuthenticationService -> UserService : saveUser(user)
        activate UserService
        activate DB
        UserService --> DB : UPDATE users SET password = ...
        DB --> UserService : update success
        deactivate DB

        UserService --> AuthenticationService : save success
        deactivate UserService
        activate AuthenticationController
        AuthenticationService --> AuthenticationController : "Password successfully changed"
        deactivate AuthenticationService

        AuthenticationController --> LoginPage : show success message
        deactivate AuthenticationController
        deactivate LoginPage
    end

    @enduml
